---

- name: start rump
  service: name=rump state=started

- name: restart rump
  service: name=rump state=restarted

- name: reload rump
  service: name=rump state=reloaded

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: reload rsyslog
  service: name=rsyslog state=reloaded
